version: '3.8'

services:
  trade-sentinel:
    build: .
    container_name: trade_sentinel_app
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
